### ISSUE TITLE
AIService interaction point 

### ISSUE THREAD

**Issue by cescoffier** [geoand/quarkus-langchain4j#14]
The idea is to leverage AI services to provide a declarative interface like REST Client. 
You would describe the interaction point with the LLM using an interface and annotations.

For example:

```java
@RegisterAiService(
    name=... // Optional - override the config key, can also be named `configKey`
    chatModel = ...// String - the chat model (or streaming chat model) identified as a name. If not set, use the default one (validated and set at build time)
    tools = ...// List<String> - the list of bean identifiers providing tools (validated at build time); if not set, all tools are available
    chatMemory = ...// String - the bean identifier for the chat memory; if not set, use the default one 
    moderationModel = .. // String - the bean identifier for the chat memory; if not set, use the default one (no moderation)
    retriever = ... // String - the bean identifier of the RAG 
)
public interface MyAiService { 
  // ...
}
```

All the attributes are optional, meaning that the following snippet would use sensible defaults:
```java
@RegisterAiService
public interface MyAiService { 
  // ...
}
```

All the configurations can be set in the `application.properties` using the `quarkus.aiservices.$name.attr=value` syntax (prefix not decided yet).

While the skeleton will be doable at build time, it will not be possible to initialize everything at build time, as the RAG may connect to the store (it might be interesting to preload the in-memory store at build time, but in the general case, it would not work).

It should be possible to use fault-tolerance annotation on the `AiService` methods. (timeout, retry, or even circuit breaker...).
If OTel is available, each method would be timed and counter automatically. The outcome would also be monitored.
If an audit service is available (See #12), each method invocation will be audited. 

Other extensions:

- Tools category - in a bean providing tools, we may need security feature (authentication) or identify the tools category. Specific processing (such as authentication) can be applied before calling the tool.  That also means we need tools interceptor. We can reuse CDI interceptors. However, we may need access to the context (both the conversational context and the duplicated context).

**Comment by geoand** [comment]
I think this makes perfect sense and would be a very handy feature

**Comment by geoand** [comment]
The only thing I am wondering about is whether we can avoid using strings as identifiers...

**Comment by cescoffier** [comment]
@geoand yes, it's not great - even if validated at build time. I was thinking reusing `@Identifier` but it can be error prone. We could also accept class names. However, lots of Quarkus features uses `@Identifier`so using classname can be confusing. Also, we would need to duplicate all the attributes: one using String, one using `Class<?>`. 

While writing this comment, I like the `Class<?>` approach:

- less confusing
- IDE completion and type safe
- Can still be validated at build time (verify it's a bean)

**Comment by geoand** [comment]
Yeah, in general I prefer the class approach as well (assuming I can make it work, which I _believe_ won't be an issue)

**Comment by geoand** [comment]
I'll start looking into this

**Comment by maxandersen** [comment]
> While writing this comment, I like the `Class<?>` approach:

how would that look?

in general, I think something like the suggested could be useful for some usecases but my current experiments feels more dynamic than this can capture but definitely think something in this direction is interesting.

i'm not super happy with the term Tool but it is langchain "terminology" so makes sense. As long as we can imagine these don't necessarily has @Tool annotations but also openapi defs or even restcilent interfaces directly would work.

**Comment by geoand** [comment]
> how would that look?

The way I see it, when you are going to use such an API it means that you are not going to be doing dynamic stuff - you are using annotations after all :).

**Comment by geoand** [comment]
I have an absolute basic example of this working, so I hope I can complete the general idea by tomorrow.

**Comment by geoand** [comment]
Just for posterity's sake, I'll add that https://github.com/geoand/quarkus-langchain4j/pull/21 introduced the basic functionality described here.

We still need work for observability etc.
