### ISSUE TITLE
master should be named main

### ISSUE THREAD

**Issue by maxandersen** [geoand/quarkus-langchain4j#4]
should happen automatically on new repos but seems was missed on this one.

**Comment by geoand** [comment]
We'll do this when we move to Quarkiverse as @cescoffier has an easy way to do this, but because the repo is personal, I can't add admins (or at least that's what I think)

**Comment by maxandersen** [comment]
Upto you. But it's easy. 

You just rename it in github and it will tell you you the git command to run locally - or simply just reclone. It requires no big magic.
